# Configuration

os:
  - linux
#  - windows
language: cpp
# compiler:
#  - gcc
#  - clang

addons:
  apt:
    packages:
      - gcc-avr
      - avr-libc
      - doxygen
      - cppcheck
      - cpputest
      - graphviz
      - socat
before_install:
  - pip install --user cpp-coveralls
install: skip
jobs:
  allow_failures:
    - os: windows
  include:
    - stage: Check clang linux code
      compiler: clang
      script:
        - make
        - make install DESTDIR=test_path
        - ./.travis/check_install.sh . test_path
    - stage: Check gcc linux code
      compiler: gcc
      script:
        - make
        - make docs 1> /dev/null
#        - ./.travis/run_tests.sh
        - make clean
        - make EXTRA_CPPFLAGS="--coverage" check
      after_success:
        - coveralls -b . --exclude docs --exclude extra --exclude unittest --exclude bld --exclude tools --exclude examples --gcov-options '\-lp'
    - stage: Check avr code
      script:
        - make ARCH=avr

