.PHONY: unittest check clean_unittest

OBJ_UNIT_TEST = \
        unittest/main.o \
        unittest/hal_tests.o \

unittest: $(OBJ_UNIT_TEST) library
	$(CXX) $(CPPFLAGS) -o $(BLD)/unit_test $(OBJ_UNIT_TEST) -L$(BLD) -lm -pthread -ltinyhal -lCppUTest -lCppUTestExt

check: unittest
	$(BLD)/unit_test

clean: clean_unittest

clean_unittest:
	rm -rf $(OBJ_UNIT_TEST) $(OBJ_UNIT_TEST:.o=.gcno) $(OBJ_UNIT_TEST:.o=.gcda)
